plugins {
    id 'com.android.application'
}

android {
    namespace 'nl.jochem.dm12picker'
    compileSdk 36

    defaultConfig {
        applicationId "nl.jochem.dm12picker"
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName "1.8"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
